variables:
  CIBW_SKIP: "cp27-*"
  TWINE_USERNAME: "codypiersall"
  CIBW_TEST_REQUIRES: "pytest pytest-asyncio pytest-trio trio"
  CIBW_TEST_COMMAND: "pytest -s -v {project}/test"

jobs:
- job: linux
  variables:
    CIBW_SKIP: "cp27-* cp38-*"
    # need newer version of cmake than is available
    CIBW_BEFORE_BUILD: "yum install -y ninja-build && pip install cmake"
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.1.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.1.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
    # TODO: can't use ninja for now because Ninja doesn't take architecture
    # arguments, so we would need to figure out the right Visual Studio version
    # to use, but we're going to punt on that decision for a while.
    # - script: choco install ninja -y
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.1.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
