#! /bin/bash
#
# Uses sed and cpp to get nng.h into a form cffi can swallow.
# removes #includes,
echo "// THIS FILE WAS AUTOMATICALLY GENERATED BY $0" > nng_api.h
sed '/^#include/d' nng/src/nng.h | cpp | sed 's/^#.*$//g' | sed '/^$/d' >> nng_api.h
